export type ToolsType =
	| "bash"
	| "web_search"
	| "read_file"
	| "edit_file"
	| "write_file"
	| "delegate_to_subagent"
	| "load_skill"
	| "compact"
	| "task_create"
	| "task_update"
	| "task_list"
	| "task_get"
	| "background_run"
	| "background_check"
	| "background_list"
	| "background_cancel";
