export type ToolsType =
  | "bash"
  | "read_file"
  | "edit_file"
  | "write_file"
  | "todo_write"
  | "delegate_to_subagent"
  | "load_skill"
  | "compact"
  | "task_create"
  | "task_update"
  | "task_list"
  | "task_get"
  | "background_run"
  | "background_check";
